/**
 * @muster/db — Shared database record types.
 *
 * These types define the shape of records stored in both:
 * - Browser (IndexedDB via Dexie.js)
 * - Relay server (SQLite via better-sqlite3)
 *
 * Both implementations store the same data — only the storage engine differs.
 */

/** A single chat message as stored in the database. */
export interface DBMessage {
  /** UUID v4 generated by the sender. Primary key. */
  messageId: string;

  /** Channel ID this message belongs to. Indexed. */
  channel: string;

  /** Message content (plaintext or E2E encrypted string). */
  content: string;

  /** Ed25519 public key hex of the sender. */
  senderPublicKey: string;

  /** Human-readable username of the sender. */
  senderUsername: string;

  /** Unix timestamp in milliseconds. Indexed. */
  timestamp: number;

  /** Ed25519 signature of the original payload. */
  signature: string;
}

/** A channel subscription record (browser only — tracks last sync time). */
export interface DBChannelSync {
  /** Channel ID. Primary key. */
  channelId: string;

  /** Timestamp of the last successfully synced message. */
  lastSyncTimestamp: number;
}
