/**
 * WebSocket Relay Protocol — Message Types
 *
 * These types define every message that flows between clients and
 * the relay node over WebSocket. They are used by both apps/web
 * (browser client) and apps/relay (relay server).
 *
 * ADD THIS FILE to packages/protocol/src/ and re-export from index.ts:
 *   export * from './ws-messages';
 */

// =================================================================
// Authentication
// =================================================================

/** Sent by relay → client immediately after WebSocket connects. */
export interface AuthChallengeMsg {
  type: 'AUTH_CHALLENGE';
  payload: {
    /** Random 32-byte hex string. Client must sign this. */
    challenge: string;
  };
  timestamp: number;
}

/** Sent by client → relay in response to AUTH_CHALLENGE. */
export interface AuthResponseMsg {
  type: 'AUTH_RESPONSE';
  payload: {
    /** Ed25519 public key hex of the client. */
    publicKey: string;
    /** Ed25519 signature of the challenge string. */
    signature: string;
    /** Human-readable username. */
    username: string;
  };
  timestamp: number;
}

/** Sent by relay → client after verifying AUTH_RESPONSE. */
export interface AuthResultMsg {
  type: 'AUTH_RESULT';
  payload: {
    success: boolean;
    reason?: string;
  };
  timestamp: number;
}

// =================================================================
// Pub/Sub — Channel subscription and messaging
// =================================================================

/** Sent by client → relay to subscribe to one or more channels. */
export interface SubscribeMsg {
  type: 'SUBSCRIBE';
  payload: {
    /** Array of channel IDs to subscribe to. */
    channels: string[];
  };
  timestamp: number;
}

/** Sent by client → relay to unsubscribe from channels. */
export interface UnsubscribeMsg {
  type: 'UNSUBSCRIBE';
  payload: {
    channels: string[];
  };
  timestamp: number;
}

/** Sent by client → relay to publish a message to a channel. */
export interface PublishMsg {
  type: 'PUBLISH';
  payload: {
    /** Target channel ID. */
    channel: string;
    /** Message content (plaintext or E2E encrypted). */
    content: string;
    /** Unique message ID (UUID v4, generated by the sender). */
    messageId: string;
    /** Unix timestamp in milliseconds. */
    timestamp: number;
  };
  /** Ed25519 signature of JSON.stringify(payload). */
  signature: string;
  /** Sender's Ed25519 public key hex. */
  senderPublicKey: string;
}

/** Sent by relay → subscribed clients when a message is published. */
export interface ChannelMessageMsg {
  type: 'MESSAGE';
  payload: {
    channel: string;
    content: string;
    messageId: string;
    timestamp: number;
    senderPublicKey: string;
    senderUsername: string;
  };
  /** Original signature from the sender (relay does not re-sign). */
  signature: string;
}

// =================================================================
// Presence
// =================================================================

/** Sent by relay → clients whenever the online list changes. */
export interface PresenceMsg {
  type: 'PRESENCE';
  payload: {
    channel: string;
    users: Array<{
      publicKey: string;
      username: string;
      status: string;
    }>;
  };
  timestamp: number;
}

// =================================================================
// Sync (used from R2 onwards — defined here for protocol stability)
// =================================================================

/** Sent by client → relay to request missed messages. */
export interface SyncRequestMsg {
  type: 'SYNC_REQUEST';
  payload: {
    /** Channel to sync. */
    channel: string;
    /** Fetch messages newer than this Unix timestamp (ms). */
    since: number;
  };
  timestamp: number;
}

/** Sent by relay → client with the missed messages. */
export interface SyncResponseMsg {
  type: 'SYNC_RESPONSE';
  payload: {
    channel: string;
    messages: ChannelMessageMsg['payload'][];
  };
  timestamp: number;
}

// =================================================================
// Error
// =================================================================

/** Sent by relay → client on protocol-level errors. */
export interface RelayErrorMsg {
  type: 'ERROR';
  payload: {
    code: string;
    message: string;
  };
  timestamp: number;
}

// =================================================================
// Union type for type-safe message handling
// =================================================================

export type RelayMessage =
  | AuthChallengeMsg
  | AuthResponseMsg
  | AuthResultMsg
  | SubscribeMsg
  | UnsubscribeMsg
  | PublishMsg
  | ChannelMessageMsg
  | PresenceMsg
  | SyncRequestMsg
  | SyncResponseMsg
  | RelayErrorMsg;
